name: Container Registry

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364b9f6c2b # v4.2.2
      - uses: docker/setup-buildx-action@f95ce51e3e7e48a329fe601a034c48b1a5d5ce04 # v3.0.0
      - uses: docker/login-action@9780b0c442cba91bfcf7f8bf4445479c39fd33f2 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@4f58ea07229d58d0b94b9bbb997dd19e6713a314 # v6.9.0
        if: hashFiles('Dockerfile') != ''
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
